receivers:
  otlp:
    protocols:
      grpc:

exporters:
  awsxray:

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
